### ISSUE TITLE
Error occurred in Python command: No frame selected

### ISSUE THREAD

**Issue by mohsininayatkhan** [openresty/nginx-gdb-utils#7]
I am new to linux and nginx and I am trying to use 'nginx-gdb-utils' to analyze luajit, and getting the following error while executing the gdb commands. 

(gdb) lbt full
Traceback (most recent call last):
  File "luajit21.py", line 511, in invoke
    L = get_cur_L()
  File "luajit21.py", line 127, in get_cur_L
    mL = get_global_L()
  File "luajit21.py", line 113, in get_global_L
    gL, _ = gdb.lookup_symbol("globalL")
gdb.error: No frame selected.
Error occurred in Python command: No frame selected.
(gdb) lvmst
Traceback (most recent call last):
  File "luajit21.py", line 597, in invoke
    L = get_cur_L()
  File "luajit21.py", line 127, in get_cur_L
    mL = get_global_L()
  File "luajit21.py", line 113, in get_global_L
    gL, _ = gdb.lookup_symbol("globalL")
gdb.error: No frame selected.
Error occurred in Python command: No frame selected.

Can you please help me to identify the issue.

**Comment by agentzh** [comment]
@mohsininayatkhan Seems like you are running the commands in a wrong context where no code is running? Maybe starting your Lua app and break in the middle (like hitting Ctrl-C in the gdb session while executing the "start" or "continue" gdb commands or setting a breakpoint yourself).

**Comment by mohsininayatkhan** [comment]
Thanks @agentzh for your reply. 

Basically I have OpenResty installed on the machine and observed that there are some memory leaks while downloading a large size file through http request.

Can you please help me how can I debug it to find the problem area.

Thanks

**Comment by agentzh** [comment]
@mohsininayatkhan Maybe it's not really a memory leak but just that the default GC pace is not enough for your usage, hence the temporary memory usage spikes. Maybe you could consider using streaming processing for large responses (instead of fully buffering everything in memory at once) and/or adjust the LuaJIT GC parameters (like "setpause"). Or maybe your Lua code has memory leaks (like an ever growing globally shared Lua table or Lua string).

BTW, the lgcstat and lgcpath commands provided by this project are particularly useful in debugging GC-managed memory issues.

**Comment by mohsininayatkhan** [comment]
is it save to call collectgarbage("collect") at the end of lua code?
Please suggest

**Comment by agentzh** [comment]
Tuning "setpause" is safer since "collect" is very expensive since it enforces full GC cycles.

**Comment by agentzh** [comment]
But still, avoiding allocating too many short-lived Lua GC objects (closures, tables, strings, and etc) in your own Lua code logic can be much much more effective and efficient.

**Comment by mohsininayatkhan** [comment]
customized the following code

https://github.com/caquino/ranger/blob/master/content.lua

to generate chunks

**Comment by agentzh** [comment]
@mohsininayatkhan Sorry, still too large for me to follow quickly.

**Comment by mohsininayatkhan** [comment]
Hello @agentzh, is there any step-by-step help available regarding how to debug code using this tool?

**Comment by agentzh** [comment]
@mohsininayatkhan Please let me know how I can improve the existing documentation of this project. I tried to give you those detailed gdb steps above but it seems that you still failed to follow. Alas.
